# Generated by Django 5.1.2 on 2024-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(max_length=700),
        ),
    ]
